"""empty message

Revision ID: 0b465ce1ae1d
Revises: bdd55b4240b8
Create Date: 2025-04-25 19:13:28.930271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b465ce1ae1d'
down_revision = 'bdd55b4240b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge')
    op.drop_table('user_exercise')
    with op.batch_alter_table('calisthenic_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_a_challenge', sa.Boolean(), nullable=False))

    with op.batch_alter_table('cardio_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_a_challenge', sa.Boolean(), nullable=False))
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_a_challenge', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.drop_column('is_a_challenge')

    with op.batch_alter_table('cardio_record', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('is_a_challenge')

    with op.batch_alter_table('calisthenic_record', schema=None) as batch_op:
        batch_op.drop_column('is_a_challenge')

    op.create_table('user_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weighted_exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('calisthenic_exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('cardio_exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['calisthenic_exercise_id'], ['calisthenic_exercises.id'], ),
    sa.ForeignKeyConstraint(['cardio_exercise_id'], ['cardio_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weighted_exercise_id'], ['weighted_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('challenger_id', sa.INTEGER(), nullable=False),
    sa.Column('challenged_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('record_to_complete', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['user_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
