"""empty message

Revision ID: bdd55b4240b8
Revises: cc19e12f5b95
Create Date: 2025-04-23 21:59:42.365165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd55b4240b8'
down_revision = 'cc19e12f5b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calisthenic_exercise')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calisthenic_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
