"""initial

Revision ID: cc19e12f5b95
Revises: 
Create Date: 2025-04-23 21:55:53.066877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc19e12f5b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weighted_exercise')
    op.drop_table('cardio_exercise')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weighted_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
